before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    id: aws-get-token 
    main: ./main.go
    binary: bin/aws-get-token
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Tag }} -X main.commit={{ .Commit }}
archives:
  - id: binary
    format: binary
    name_template: "{{ .ProjectName }}_{{ .Os }}-{{ .Arch }}"
  - id: archive
    format: tar.gz
    replacements:
      darwin: macOS
    files:
      - LICENSE*
      - README*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-{{ .ShortCommit }}"
release:
  draft: false 
